---
title: "Spokes"
author: "Luis Ángel Rodríguez García" 
date: '2022-05-31'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rprojroot)
library(here)
print(here())
library(knitr)
library(pscsne)
library(rgl)
rgl::setupKnitr()
```

## Spokes

Sample on the $(\mathbb{S}^2)^{168}$ where $p=2$, $r=168$ and $n=177$.

```{r}
load(paste(here("data-raw", "spokes"), "spokes.RData", sep = "/"))
n <- dim(dirs)[1]
p <- dim(dirs)[3] - 1
r <- dim(dirs)[2]
spokes <- array(0, c(n, p + 1, r))
for(i in seq_len(r)) {
  spokes[, , i] <- dirs[, i, ]
}

# Plot subjects for each spok
rgl::open3d()
rgl::mfrow3d(nr = 12, nc = 14, sharedMouse = TRUE)
n <- 10
col <- rainbow(n, alpha = 0.8)
for (i in seq_len(ncol(dirs))) {
  col_i <- col # ids_labs + 1
  rgl::plot3d(dirs[1:n, i, ], xlim = c(-1, 1), ylim = c(-1, 1), zlim = c(-1, 1),
              col = col_i, axes = FALSE, box = FALSE, xlab = "",
              ylab = "", zlab = "")
  rgl::spheres3d(0, 0, 0, radius = 1, col = "lightblue", lit = FALSE,
                 alpha = 0.5)
}
```

Let's calculate the rho parameters based on a perplexity of 30:

```{r cache=TRUE}

rho_spokes_perp25 <- rho_optim_bst(spokes, 25)

```

First, let's reduce to dimension $\mathbb{S}^1$ then $d=1$ (circumference):

```{r cache=TRUE}
res_pscsne <- psc_sne(spokes, d = 1, rho_psc_list = rho_spokes_perp25,
             colors = ifelse(ids_labs, 2, 1), show_prog = TRUE)

Y <- res_pscsne$best_Y
```

Let's apply the kernel means shift function to see what clusters identifies.

```{r}
res_kms_dir_Y_1 <- kms_dir(x = Y, data = Y)

plot(Y[, 1], Y[, 2], col = res_kms_dir_Y_1$cluster, xlim = c(-1, 1), 
     ylim = c(-1, 1))

polygon(x = cos(seq(0, 2 * pi, length.out = 100)),
        y = sin(seq(0, 2 * pi, length.out = 100)))
```

Now we are going to reduce to dimension $\mathbb{S}^2$ then $d=2$ (sphere):

```{r cache=TRUE}
res_pscsne <- psc_sne(spokes, d = 2, rho_psc_list = rho_spokes_perp25,
             colors = ifelse(ids_labs, 2, 1), show_prog = TRUE)

Y <- res_pscsne$best_Y
```

Let's do the same applying the kms onto the sphere.

```{r}
res_kms_dir_Y <- kms_dir(x = Y, data = Y)
colors <- res_kms_dir_Y$cluster

# Sequence from -180 to 180 by an step of 15 in radians
seq_rad <- seq(-pi, pi, by = pi / 30)
# Meridian calculates as theta = 0 and phi = i
# where i is the radians
meridian <- do.call(rbind, lapply(seq_rad, function(i) c(0, i)))
equator <- do.call(rbind, lapply(seq_rad, function(i) c(i, pi/2)))

sd3 <- scatterplot3d::scatterplot3d(Y, xlim = c(-1, 1), ylim = c(-1, 1),
                             zlim = c(-1, 1), color = colors,
                             pch = c('+', '-')[ifelse(sign(Y[, 2]) == 1, 1, 2)])
sd3$points3d(DirStats::to_sph(th = meridian[, 1], ph = meridian[, 2]),
             type = "l", lty = 3)
sd3$points3d(DirStats::to_sph(th = equator[, 1], ph = equator[, 2]),
             type = "l", lty = 3)
```

